feat: add Kafka support to MeterReportService
apache/skywalking-python pull request #243
Opened 2022-10-18 14:59 UTC by jiang1997

https://github.com/apache/skywalking-python/pull/238

Thanks to @Superskyyy's assistance.

2022-10-18 21:07 UTC, Superskyyy commented
LGTM and congratulations on finishing all parts of the OSPP task! I appreciate your contribution and look forward to more haha.

2022-10-18 21:14 UTC, Superskyyy requested changes

2022-10-18 21:14 UTC, Superskyyy commented on tests/e2e/case/kafka/e2e.yaml
>      # TODO: Metric Collection Implementation is not merged https://github.com/apache/skywalking/issues/7084
remove these

2022-10-18 21:15 UTC, Superskyyy commented
Just some minor stuff, others are good. ^

2022-10-19 01:35 UTC, kezhenxu94 approved these changes
please address @Superskyyy 's review and LGTM.

2022-10-19 06:30 UTC, jiang1997 commented on skywalking/client/kafka.py
> +        value = bytes(collection.SerializeToString())
I tried and it failed to pass tests.
After some searching, I found that the default string encoding of Java is `UTF-8` and the default string encoding of python3 is `UTF-16` or `UTF-32`. So the conversion is needed.

2022-10-19 06:39 UTC, jiang1997 commented on skywalking/client/kafka.py
> +        value = bytes(collection.SerializeToString())
I have tried and it faild to pass the tests.
After some searching, I found that the default encoding of `org.apache.kafka.common.serialization.StringDeserializer` is `UTF-8` and the default string econding of python3 is `UTF-16` or `UTF-8`. So the conversion is needed.

2022-10-19 08:01 UTC, jiang1997 commented
> 

I'm also looking forward to attending aiops.

2022-10-20 23:01 UTC, Superskyyy commented on skywalking/client/kafka.py
> +        value = bytes(collection.SerializeToString())
Actually I meant the value part, the key part is still needed. Sorry didn't make myself clear.

2022-10-21 04:01 UTC, jiang1997 commented on skywalking/client/kafka.py
> +        value = bytes(collection.SerializeToString())
You are right.

2022-10-21 04:14 UTC, kezhenxu94 approved these changes

2022-10-21 14:27 UTC, Superskyyy approved these changes

2022-10-21 14:28 UTC, merged

2022-10-21 14:28 UTC, Superskyyy commented
Thank you.

2022-10-21 15:05 UTC, wu-sheng commented
@Superskyyy Are we going to have a 1.0.0 release shortly? I noticed there are only 2 left on https://github.com/apache/skywalking/milestone/140

2022-10-22 08:06 UTC, Superskyyy commented
> @Superskyyy Are we going to have a 1.0.0 release shortly? I noticed there are only 2 left on [apache/skywalking/milestone/140](https://github.com/apache/skywalking/milestone/140)

I think so, the preforking behavior relates to somewhat weird issues in upstream dependencies that cannot be solved easily. I will try to take another look soon and go for 1.0.0, regardless if it's resolved.