add GreenletProfiler
apache/skywalking-python pull request #246
Opened 2022-10-25 02:47 UTC by westarest

2022-10-25 02:52 UTC, westarest commented
it is a draft, but it can work with threading model and greenlet model automatically now. it needs more things:
test cases

2022-10-25 03:28 UTC, wu-sheng commented
Verifying through e2e profiling case would be a good place to start.

2022-10-25 03:33 UTC, wu-sheng commented
Profiling e2e has been included in the main repo, https://github.com/apache/skywalking/blob/317d539371c588c4754029134ad76087ecb6d0cd/.github/workflows/skywalking.yaml#L435-L454 powered by our e2e-infra tool, https://skywalking.apache.org/docs/skywalking-infra-e2e/next/readme/

You could learn how we run tests using the latest agent with real OAP/SkyWalking backend, and verify the result through SkyWalking CLI through this tool.

2022-10-25 03:37 UTC, westarest commented
> thank you, it is the docs what I need

2022-10-28 16:32 UTC, westarest commented
there is something wrong when profiling start:
```
skywalking [Thread-127] [DEBUG] profile task [1666974131787_ZTJlLXNlcnZpY2UtcHJvdmlkZXI=.1] for endpoint [/artist] started
Traceback (most recent call last):
  File "src/gevent/_waiter.py", line 122, in gevent._gevent_c_waiter.Waiter.switch
  File "/skywalking-python/venv/lib/python3.6/site-packages/apache_skywalking-0.8.0-py3.6.egg/skywalking/profile/profile_context.py", line 329, in callback
    agent.add_profiling_snapshot(snapshot)
  File "/skywalking-python/venv/lib/python3.6/site-packages/apache_skywalking-0.8.0-py3.6.egg/skywalking/agent/__init__.py", line 288, in add_profiling_snapshot
    __snapshot_queue.put(snapshot)
  File "/usr/local/lib/python3.6/queue.py", line 126, in put
    with self.not_full:
  File "/usr/local/lib/python3.6/threading.py", line 240, in __enter__
    return self._lock.__enter__()
  File "src/gevent/_semaphore.py", line 278, in gevent._gevent_c_semaphore.Semaphore.__enter__
  File "src/gevent/_semaphore.py", line 279, in gevent._gevent_c_semaphore.Semaphore.__enter__
  File "src/gevent/_semaphore.py", line 180, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "/skywalking-python/venv/lib/python3.6/site-packages/gevent/thread.py", line 121, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
  File "src/gevent/_semaphore.py", line 180, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 249, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 68, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
2022-10-28T16:22:34Z <built-in method switch of gevent._gevent_cgreenlet.Greenlet object at 0x7ff213196a48> failed with BlockingSwitchOutError
```

2022-11-01 16:04 UTC, Superskyyy requested changes

2022-11-01 16:04 UTC, Superskyyy commented on .github/workflows/CI.yaml
> +          - name: proflinig_threading
```suggestion
          - name: profiling_threading
```

2022-11-02 15:54 UTC, Superskyyy commented
Generally looks good to me. @kezhenxu94 can you take a look? I'm not very familiar with the profiling feature.

2022-11-04 17:12 UTC, Superskyyy commented
The sonatype bug can be ignored, since it's testing code. LGTM.

2022-11-04 17:12 UTC, Superskyyy submitted a review, later dismissed

2022-11-04 17:17 UTC, Superskyyy commented
We need to update `changes.md` to reflect the new feature. And also we will need documentation. The original documentation for threading-profiling was posted to here https://skywalking.apache.org/blog/2021-09-12-skywalking-python-profiling/, now with the addition of Greenlet Profiler, it will be better to move it back to our repository and add the corresponding part for greenlet. @westarest, can you add the docs in the next PR?

2022-11-05 01:05 UTC, kezhenxu94 submitted a review, later dismissed

2022-11-05 01:05 UTC, kezhenxu94 commented on skywalking/profile/profile_context.py
> +        if greenlet.__version__ < '2.0.0':
This looks error prone. Can you use the `packaging` module to parse and compare the version?

2022-11-05 03:34 UTC, westarest commented
> We will need documentation. The original documentation for threading-profiling was posted to here https://skywalking.apache.org/blog/2021-09-12-skywalking-python-profiling/, now with the addition of Greenlet Profiler, it will be better to move it back to our repository and add the corresponding part for greenlet. @westarest, can you work on the docs in the next PR?

no problem. I can post a document about the difference between the Threading profiler  and the Greenlet profiler that I committed.

2022-11-05 03:46 UTC, kezhenxu94 approved these changes
Thanks!

2022-11-05 04:16 UTC, wu-sheng reviewed
Cool. @westarest Would you like to write a new blog for this feature, to introduce why it is important, and how you implement this, and use it?

I believe this is a very important and valuable blog.

2022-11-05 04:31 UTC, merged